name: Elecrow ESP32P4 based panels interface
version: "1.0.8"
slug: crow_ws_panel
description: Home Assistant Kiosk for Elecrow ESP32P4 Advance panels
url: https://github.com/fintros/crow-ha
arch:
  - amd64
  - aarch64
init: false
apparmor: false
ports:
  "3000/tcp": 3000
ports_description:
  "3000/tcp": WebSocket stream + touch input for the panel device

