name: Elecrow ESP32P4 interface
version: "1.0.3"
slug: crow_ws_panel
description: Home Assistant Browser for Elecrow ESP32P4 Advance panel
url: https://github.com/fintros/crow-ha
arch:
  - amd64
  - aarch64
init: false
apparmor: false
ports:
  "3000/tcp": 3000
ports_description:
  "3000/tcp": WebSocket stream + touch input for the panel device

